apiVersion: v1
kind: Service
metadata:
  name: bluegreenservice
spec:
  selector:
    app: green
  ports:
  - protocol: TCP
    port: 8005 # Expose port 8005 on the Service
    targetPort: 80
  type: NodePort

