---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blue
  labels:
    app: blue
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  DB_HOST: database
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: blue
  labels:
    app: blue
  annotations: 
    argocd.argoproj.io/sync-wave: "1"
stringData:
  DB_NAME: database
  DB_USER: user1
  DB_PASSWORD: password
  DB_ADMIN_PASSWORD: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: blue
  annotations:
    description: Defines how to deploy the application server
    template.alpha.openshift.io/wait-for-ready: "true"
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  strategy:
    type: Recreate
  template:
    metadata:
      name: blue
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: quay.io/redhattraining/exoplanets:v1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: blue
        - secretRef:
            name: blue
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          limits:
            memory: 1Gi
        securityContext:
          privileged: false
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: blue
  labels:
    app: blue
  annotations:
    description: Exposes and load balances the application pods
    service.alpha.openshift.io/dependencies: '[{"kind": "Service", "name": "database"}]'
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: blue
  ports:
  - name: web
    port: 8080
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: blue
  labels:
    app: blue
  annotations: 
    argocd.argoproj.io/sync-wave: "3"
spec:
  host: "blue-blue-green.apps.ocp4.smartek.ae"
  to:
    kind: Service
    name: blue
