# Use an official Nginx runtime as the base image
FROM nginx:latest

# Copy version 1 HTML into the Nginx web server's root directory
COPY green.html  /usr/share/nginx/html/index.html

# Expose port 80 to allow external access
EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]                                    
