apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: 
    argocd.argoproj.io/sync-wave: "0"
  name: test-app-secretless
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: my-app
  name: my-app
  namespace: test-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: test-app-secretless
      containers:
      # Insert your container definition here
      # Ensure it's configured to point to Secretless for the DB connection
      #
      - name: my-app
        image: quay.io/redhattraining/famous-quotes
        ports: 
        - containerPort: 8000
        env: 
          - name: QUOTES_USER
            value: localhost:3306
          - name: QUOTES_PASSWORD
            value: localhost:3306
          - name: QUOTES_DATABASE
            value: "items"
      - name: secretless
        image: cyberark/secretless-broker:latest
        imagePullPolicy: IfNotPresent 
        args: ["-f", "/etc/secretless/secretless.yml"]
        ports:
          - containerPort: 3306
        env:
          - name: CONJUR_AUTHN_LOGIN
            value: "host/service-account-based-app"
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_AUTHN_URL
            value: https://conjur-lb.smartek.ae/authn-k8s/dev-cluster
          - name: CONJUR_APPLIANCE_URL
            value: https://conjur-lb.smartek.ae
          - name: CONJUR_ACCOUNT
            value: smartek
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: conjur-connect
                key: CONJUR_SSL_CERTIFICATE
                # envFrom:
                #- configMapRef:
                #name: conjur-connect
        volumeMounts:
          - mountPath: /etc/secretless
            name: config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: secretless-config
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  annotations: 
    argocd.argoproj.io/sync-wave: "0"
  name: my-app
  namespace: test-app-namespace
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: my-app
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    openshift.io/host.generated: "true"
  name: my-app
  namespace: test-app-namespace
spec:
  host: my-app-test-app-namespace.apps.ocp4.smartek.ae
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: my-app
