pipeline {
    agent {
      kubernetes {
        yaml '''
        apiVersion: v1
        kind: Pod
        metadata:
          labels:
            label: jenkins-build
        spec:
          serviceAccountName: nonrootbuilder-sa
          containers:
          - name: podman-builder
            image: quay.io/rkhelifi/podman-builder:v1
            command:
              - cat
            tty: true
            env:
              - name: HOME
                value: /home/jenkins/agent 
'''
    }
  }
    stages {
        stage('Debug Podman PATH') {
           steps {
              container('podman-builder') {
               script {
            // Print PATH and check podman location
            sh 'echo $PATH'
            sh 'which podman'
            sh 'podman --version'
          }
        }
      }
    }  
    
 
       stage('Checkout') {
      steps {
        // Checkout the repository
        git url: 'https://github.com/rihab123456789/openshift-gitops-getting-started.git', branch: 'main'
      }
    }
        stage('Build Image') {
            steps { 
                container('podman-builder') {
                script {
                   sh 'ls -l ci-cd'
            
            // Build the image with podman, specifying the path to the Containerfile
                   sh 'podman build -t hello-gitops:${BUILD_NUMBER}-v1 -f ci-cd/Containerfile .'
                    // Login to Quay.io registry (replace with your credentials)
                    sh 'podman login -u rkhelifi@smartek.ae -p khelifi123 quay.io'

                    // Tag the image for Quay.io
                    sh 'podman tag hello-gitops:${BUILD_NUMBER}-v1 quay.io/rkhelifi/hello-gitops:${BUILD_NUMBER}-v1'

                    // Push the image to Quay.io
                    sh 'podman push quay.io/rkhelifi/hello-gitops:${BUILD_NUMBER}-v1'
                }
            }
        } } 
     stage('Update Deployment Manifest') {
    steps {
        script {
          sh "sed -i 's#quay.io/rkhelifi/hello-gitops:v1#quay.io/rkhelifi/hello-gitops:${BUILD_NUMBER}-v1#g' ci-cd/app/deployment.yaml"
                }
        }

    }
   
     stage('Commit & Push to Git Repository') {
      steps {
          script { 
            sh "git config --global user.email 'rkhelifi@smartek.ae'"  // Replace with your email
            sh "git config --global user.name 'Rihab'"  
            sh 'git add "."'  // Add only the updated file
            sh "git commit -am 'Updated image version for Build #${BUILD_NUMBER}'"
            // Assuming you have configured Git credentials (avoid exposing credentials)
            sh 'git push origin main'  // Adjust branch name if needed
          }
        }
    }

    }
} 

